development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  linkedin_consumer_key: <%= ENV['LINKEDIN_CONSUMER_KEY'] %>
  linkedin_consumer_secret: <%= ENV['LINKEDIN_CONSUMER_SECRET'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  linkedin_consumer_key: <%= ENV['LINKEDIN_CONSUMER_KEY'] %>
  linkedin_consumer_secret: <%= ENV['LINKEDIN_CONSUMER_SECRET'] %>
